### ISSUE TITLE
Some questions about SPA

### ISSUE THREAD

**Issue by HSXkeeny** [huoxiangzuo/SPA#1]
Hello, bro, I'm interested in your paper "SPA: Self-Peripheral-Attention for Central-Peripheral Interactions in Endoscopic Image Classification and Segmentation", and I have a few questions for you.

Firstly, what motivated you to submit this paper to NeurIPS? Does it align with the research direction of NeurIPS?

Secondly, could you elaborate on how the Self-Peripheral-Attention module extracts image features? What kind of strategies and methods are used in your model, and why does the accuracy improve?

In addition, I would like to understand the main ideas and thoughts behind this paper, as well as the innovative aspects of your work.

Finally, what are your expectations for this paper being accepted at NeurIPS? Are there any special considerations or expectations?

I look forward to your reply, thank you very much!

**Comment by huoxiangzuo** [comment]
Bro, are u serious?
