### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by KUKUDAS95** [huoxiangzuo/SPA#2]
Does this experiment have a pretrained model

**Comment by huoxiangzuo** [comment]
> hello! I'm very intersted in your job. can you provide class_indices.json file?

class_indices.json is automatically generated based on the dataset category.

**Comment by huoxiangzuo** [comment]
> Does this experiment have a pretrained model

We do not do pre-training on large datasets such as ImageNet. On small datasets such as Kvasir, you can train from scratch. Pre-training on private datasets, we do not have permission to make them public.
